; Inno Setup Compiler Script
; Generated by Antigravity AI Coding Assistant
; This script compiles the LectureScribe PyInstaller folder into a compressed Windows installer.
; Requires Inno Setup (https://jrsoftware.org/isdl.php) to compile.

#define MyAppName "LectureScribe"
#define MyAppVersion "1.1.3"
#define MyAppPublisher "frotrue"
#define MyAppExeName "LectureScribe.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{5D8A33E2-AF1B-459E-B4A1-FA5E9E74BC79}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Place the final compiled installer setup inside the project's 'dist' folder
OutputDir=dist
OutputBaseFilename=LectureScribe_Setup
; Use Inno Setup's highest LZMA2 compression ratio (similar to 7-zip Ultra)
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern
; Set setup icon if you have one (optional)
; SetupIconFile=icon.ico

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copy all files and folders recursively from the PyInstaller output directory
Source: "dist\LectureScribe\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "THIRD_PARTY_NOTICES.md"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
; Create shortcuts in Start Menu and Desktop
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Option to launch the program immediately after installation completes
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean up folder upon uninstallation
Type: filesandordirs; Name: "{app}"
